// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComercioInteriorV2.Data.Models;

public partial class Articulo
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public decimal? PrecioUnitario { get; set; }

    public int? EstaActiva { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();
}