// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ComercioInteriorV2.Data.Models;

public partial class ComercioInteriorDbContext : DbContext
{
    public ComercioInteriorDbContext(DbContextOptions<ComercioInteriorDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Articulo> Articulos { get; set; }

    public virtual DbSet<DetallesFactura> DetallesFacturas { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<FormasPago> FormasPagos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Articulo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_articulos");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EstaActiva).HasColumnName("esta_activa");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precioUnitario");
        });

        modelBuilder.Entity<DetallesFactura>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_detallefactura");

            entity.ToTable("Detalles_Factura");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EstaActiva).HasColumnName("esta_activa");

            entity.HasOne(d => d.NroArticuloNavigation).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.NroArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_articulo");

            entity.HasOne(d => d.NroFacturaNavigation).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.NroFactura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_factura");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_factura");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Cliente)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("cliente");
            entity.Property(e => e.EstaActiva).HasColumnName("esta_activa");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.Pago).HasColumnName("pago");

            entity.HasOne(d => d.PagoNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.Pago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_pago");
        });

        modelBuilder.Entity<FormasPago>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_forma_pago");

            entity.ToTable("Formas_Pago");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EstaActiva).HasColumnName("esta_activa");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}