// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComercioInteriorV2.Data.Models;

public partial class DetallesFactura
{
    public int Id { get; set; }

    public int NroFactura { get; set; }

    public int NroArticulo { get; set; }

    public int? Cantidad { get; set; }

    public int? EstaActiva { get; set; }

    public virtual Articulo NroArticuloNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}