// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComercioInteriorV2.Data.Models;

public partial class Factura
{
    public int Id { get; set; }

    public DateOnly? Fecha { get; set; }

    public int Pago { get; set; }

    public string Cliente { get; set; }

    public int? EstaActiva { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual FormasPago PagoNavigation { get; set; }
}