// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EnvioDeProductos.Models;

public partial class GestionEnviosContext : DbContext
{
    public GestionEnviosContext(DbContextOptions<GestionEnviosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DetalleEnvio> DetalleEnvios { get; set; }

    public virtual DbSet<Envio> Envios { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DetalleEnvio>(entity =>
        {
            entity.ToTable("DetalleEnvio");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.Comentario)
                .HasMaxLength(200)
                .HasColumnName("comentario");
            entity.Property(e => e.IdEnvio).HasColumnName("idEnvio");
            entity.Property(e => e.IdProducto).HasColumnName("idProducto");

            entity.HasOne(d => d.IdEnvioNavigation).WithMany(p => p.DetalleEnvios)
                .HasForeignKey(d => d.IdEnvio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DetalleEnvio_Envio");

            entity.HasOne(d => d.IdProductoNavigation).WithMany(p => p.DetalleEnvios)
                .HasForeignKey(d => d.IdProducto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DetalleEnvio_Producto");
        });

        modelBuilder.Entity<Envio>(entity =>
        {
            entity.ToTable("Envio");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Direccion)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("direccion");
            entity.Property(e => e.DniCliente).HasColumnName("dniCliente");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("estado");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.PalabraSecreta)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("palabraSecreta");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producto__3213E83F008E635F");

            entity.ToTable("Producto");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nombre");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}